[package]
name = "rusty-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
serde_json = "1.0"
hostname = "0.3"
num_cpus = "1.16"
nu-table = "0.91"
rustc_version_runtime = "0.3.0"